spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

token:
  issuer: sasstyle.com
  secret: sasstyle_token
  expiration_time: 86400000

springdoc:
  version: v1